#-------------------------------
# General Site Settings

title: Magee Music Group
description: This site was built to showcase the Magee Music Group
email: mageemusicgroup@gmail.com

menu:
- {name: 'Music', url: ''}
- {name: 'Blog', url: 'blog.html'}
- {name: 'About', url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Magee Music Group Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/1/100599977803231866160'
  rel-publisher: 'https://plus.google.com/u/1/100599977803231866160'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

about: >
  # We are the MMG
  
  [CHEFBOI RD](https://soundcloud.com/david-ochieng)
  
  [KAN$HAN THE SCHOLAR](https://soundcloud.com/kantaro-horino7)
  
  [FUJI KYLE](https://soundcloud.com/fuji-kyle/)
  
  [TUBBYT](https://soundcloud.com/prodbytubbyt/)
  
  [YOUN XENO](https://soundcloud.com/kingxeno/)


  
  


contact: >
  # Contact

  You can contact us [through email](mailto:mageemusicgroup@gmail.com) or [tweet at me](https://twitter.com/intent/tweet?text=%40music_magee) if you have any questions about our music or want to collaborate.

#-------------------------------
# Work Section

projects:
- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/music_magee'}
- {icon: 'instagram', link: 'https://www.instagram.com/mageemusicgroup/'}
- {icon: 'github', link: 'https://github.com/mageemusicgroup'}
- {icon: 'soundcloud', link: 'https://soundcloud.com/user-565891908'}
- {icon: 'envelope', link: 'mailto:mageemusicgroup@gmail.com'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCDfbGSE6S1-tT2PPglOHMvg
'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
